filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: postgres
repositories:
- name: commonground
  url: https://charts.commonground.nl/
releases:
- chart: commonground/postgres-operator
  version: 1.6.2
  name: postgres-operator
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
