# Source: postgres-operator/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.6.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: postgres-operator
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'postgres-operator'
    meta.helm.sh/release-namespace: 'postgres'
  namespace: postgres
data:
  pod_service_account_name: postgres-pod
  docker_image: registry.opensource.zalan.do/acid/spilo-13:2.0-p6
  enable_crd_validation: "true"
  enable_lazy_spilo_upgrade: "false"
  enable_pgversion_env_var: "true"
  enable_shm_volume: "true"
  enable_spilo_wal_path_compat: "false"
  etcd_host: ""
  max_instances: "-1"
  min_instances: "-1"
  repair_period: 5m
  resync_period: 30m
  workers: "8"
  replication_username: standby
  super_username: postgres
  major_version_upgrade_mode: "off"
  minimal_major_version: "9.5"
  target_major_version: "13"
  cluster_domain: cluster.local
  cluster_labels: application:spilo
  cluster_name_label: cluster-name
  enable_init_containers: "true"
  enable_pod_antiaffinity: "false"
  enable_pod_disruption_budget: "true"
  enable_sidecars: "true"
  pdb_name_format: postgres-{cluster}-pdb
  pod_antiaffinity_topology_key: kubernetes.io/hostname
  pod_management_policy: ordered_ready
  pod_role_label: spilo-role
  pod_terminate_grace_period: 5m
  secret_name_template: '{username}.{cluster}.credentials.{tprkind}.{tprgroup}'
  spilo_allow_privilege_escalation: "true"
  spilo_privileged: "false"
  storage_resize_mode: pvc
  watched_namespace: '*'
  pod_deletion_wait_timeout: 10m
  pod_label_wait_timeout: 10m
  ready_wait_interval: 3s
  ready_wait_timeout: 30s
  resource_check_interval: 3s
  resource_check_timeout: 10m
  db_hosted_zone: db.example.com
  enable_master_load_balancer: "false"
  enable_replica_load_balancer: "false"
  external_traffic_policy: Cluster
  master_dns_name_format: '{cluster}.{team}.{hostedzone}'
  replica_dns_name_format: '{cluster}-repl.{team}.{hostedzone}'
  aws_region: eu-central-1
  enable_ebs_gp3_migration: "false"
  logical_backup_docker_image: registry.opensource.zalan.do/acid/logical-backup:v1.6.2
  logical_backup_job_prefix: logical-backup-
  logical_backup_provider: s3
  logical_backup_s3_access_key_id: ""
  logical_backup_s3_bucket: my-bucket-url
  logical_backup_s3_endpoint: ""
  logical_backup_s3_region: ""
  logical_backup_s3_secret_access_key: ""
  logical_backup_s3_sse: AES256
  logical_backup_schedule: 30 00 * * *
  debug_logging: "true"
  enable_database_access: "true"
  api_port: "8080"
  cluster_history_entries: "1000"
  ring_log_lines: "100"
  enable_postgres_team_crd: "false"
  enable_teams_api: "false"
  connection_pooler_default_cpu_limit: "1"
  connection_pooler_default_cpu_request: 500m
  connection_pooler_default_memory_limit: 100Mi
  connection_pooler_default_memory_request: 100Mi
  connection_pooler_image: registry.opensource.zalan.do/acid/pgbouncer:master-16
  connection_pooler_max_db_connections: "60"
  connection_pooler_mode: transaction
  connection_pooler_number_of_instances: "2"
  connection_pooler_schema: pooler
  connection_pooler_user: pooler
