# Source: postgres-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.6.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: postgres-operator
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'postgres-operator'
    meta.helm.sh/release-namespace: 'postgres'
  namespace: postgres
